name: Custom
on:
  push:
    tags:
    - "v*"
jobs:
  release:
    name: "Custom"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: kdahal-ventera/custom-action@main
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
      
