name: Custom
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kdahal-ventera/custom-action@main
      - name: Release-Notes-Preview
  # You may pin to the exact commit or the version.
  # uses: snyk/release-notes-preview@77b57680e453abd052d6e029e84037b644251ee8
        uses: snyk/release-notes-preview@v1.6.1
